### ISSUE TITLE
Response card with more than 1 item

### ISSUE THREAD

**Issue by 1sn0s** [awslabs/aws-lex-web-ui#1]
If the response card contains more than 1 object, how would it be showing on the web interface ? as a list or carousel etc

**Comment by atoa** [comment]
I am assuming that you are referring to multiple [Generic Attachments](http://docs.aws.amazon.com/lex/latest/dg/API_runtime_GenericAttachment.html) in a response card (please correct me if this is wrong). In that case, each attachment is rendered individually as its own card.

As of now, the cards are individually inserted in the message list which may result in the cards being shown side-by-side or one-on-top-of-the-other depending on the content. Please let me know if this answers the question or if you have further questions or comments.

**Comment by 1sn0s** [comment]
Yes this answers my question.
Thank you

**Comment by atoa** [comment]
Great! I am closing this issue then 😄
