### ISSUE TITLE
Delay time between messages

### ISSUE THREAD

**Issue by urvish-patel123** [awslabs/aws-lex-web-ui#11]
Is there a way to add a delay between the message sent by user and the message posted on the iframe by Lex? Like a set 3 second delay to make the conversation seem more human-like?

**Comment by atoa** [comment]
Hi,

Unfortunately, there is no quick way to do that right now.

If you feel like hacking the code yourself, you could introduce a delay in the [postTextMessage action](https://github.com/awslabs/aws-lex-web-ui/blob/428710dc98b50f82f887aab583b4005b27898c69/lex-web-ui/src/store/actions.js#L441).  After the highlighted line in the previous link, you'd have to wedge a timeout into the promise chain (before the `pushMessage` action is called). Something like this:

```javascript
.then(response => new Promise((resolve) => {
  setTimeout(() => resolve(response), 3000);
}))
```
Please note that this would require to rebuild the code (needs a recent node.js and a unix-like development environment). Clone this repo, then issue the following commands inside of its root directory:
```shell
cd lex-web-ui
npm install
cd ../dist
make
```
Hope this helps

-- Oliver

**Comment by atoa** [comment]
I am closing this issue since it seems like the question has been answered.
