### ISSUE TITLE
Issue with session attributes in Lex Web UI & support with IE11

### ISSUE THREAD

**Issue by Samer2** [awslabs/aws-lex-web-ui#20]
I am facing issue in accessing session attributes in Lex Web UI. The session attributes gets cleared every time intent has been called. Though it works fine in Lex Console. 

On a separate note, does this supports IE11 ?

**Comment by atoa** [comment]
Hi,

> The session attributes gets cleared every time intent has been called. 

By default, the Lex Web UI resets the session attributes. The `reInitSessionAttributesOnRestart` config field under the `lex` key controls this behavior. Set it to `false` to have the session attributes persist across sessions. For example:

```json
...
  "lex": {
    "reInitSessionAttributesOnRestart": false
  }
...
```

> On a separate note, does this supports IE11 ?

Yes, IE11 is supported (text only) by including [babel polyfill](https://babeljs.io/docs/usage/polyfill/). The demo site includes it:
https://github.com/awslabs/aws-lex-web-ui/blob/293b3774b06e0b451ec21ccae1178000212264c8/src/website/index.html#L14

**Comment by Samer2** [comment]
ThankYou, it worked !!

**Comment by atoa** [comment]
Resolving

**Comment by loukotaj** [comment]
I made a new issue above because I didn't realize you could comment on closed issues, not sure which method is the best practice. Where is this config key located?
