### ISSUE TITLE
How to edit vue component and rebuild?

### ISSUE THREAD

**Issue by johnpyp** [awslabs/aws-lex-web-ui#27]
It seems like it should be obvious, but nothing is working for me.

What is the command sequence to rebuild the parent of the lex-web-ui vue component? After I build from the vue directory, how do I get that into the parent build?

Doing `npm run build` from the vue then doing `npm run build` from the parent doesn't seem to work, and I've tried other things as well.

**Comment by atoa** [comment]
Hello,

> What is the command sequence to rebuild the parent of the lex-web-ui vue component? After I build from the vue directory, how do I get that into the parent build?

The [dist/Makefile](https://github.com/awslabs/aws-lex-web-ui/blob/master/dist/Makefile) can be used to build and copy the Vue library into the parent build. Here are the commands:

```shell
# from root directory of the repo
cd dist
# requires GNU make
make
```

Let me know if this clarifies it or if you have questions/comments/suggestions.

Thanks

-- Oliver

**Comment by johnpyp** [comment]
Works great, thanks!

**Comment by DVGalarza** [comment]
@atoa I ran into errors running the Make command, so what worked for me was to run `npm run build-dist` from `~/lex-web-ui` and then copy the files from `~/lex-web-ui/dist/bundle` to `~/dist`.

**Comment by atjohns** [comment]
There is currently an issue with the build that you appear to have discovered. I will get a fix out for it asap
