### ISSUE TITLE
Run locally

### ISSUE THREAD

**Issue by jmarcos-cano** [awslabs/aws-lex-web-ui#3]
How can I run this project as shown in the image?

**Comment by atoa** [comment]
Hi Marcos,

You can run a local development environment using node js/npm. Clone the repo and cd into the `lex-web-ui` directory. From that directory, follow the instructions in: [Dependencies and Build Setup](https://github.com/awslabs/aws-lex-web-ui/blob/master/lex-web-ui/README.md#dependencies-and-build-setup).

Let me know if that answers your question.

**Comment by atoa** [comment]
Added more details about it in the [running locally](https://github.com/awslabs/aws-lex-web-ui#running-locally) section of the README. I am going to assume that this answers the question and close this issue. Feel free to re-open if you have further questions or comments.
