### ISSUE TITLE
Access denied exception only for first voice request from Web UI to Lex

### ISSUE THREAD

**Issue by SuneetPatil** [awslabs/aws-lex-web-ui#8]
Hi Team,

I have using a sample Amazon Lex web interface. Chatbot is integrated with integrated with my web page.
It is working fine with text inputs but I get the error only whenever i try to use voice input for the first time.

I couldn't start the conversation. Please try again. (AccessDeniedException: User: arn:aws:sts::XX73XXX9XXXX:assumed-role/carmobilehub_unauth_MOBILEHUB_709XXXX3X/CognitoIdentityCredentials is not authorized to perform: polly:SynthesizeSpeech)

If i use text input for the first time and then try with voice input it works fine. I guess the issue might be in lex-web-ui.mi.js file.

PLease help

Thanks,
Suneet

**Comment by atoa** [comment]
Hi Suneet,

It seems like the IAM policy associated to role of the Cognito Identity Pool doesn't have polly:SynthesizeSpeech permissions. To add the permissions, see the following steps:

1. Go to the [IAM Console](https://console.aws.amazon.com/iam/home#/home)
2. Select **Roles**
3. Once in the Roles section, find the role associated with the Cognito Identity Pool (by the log you posted above, it seems like your role name starts with *carmobilehub_unauth_MOBILEHUB_709*)
4. Click on the **Add inline policy** link
5. Select **Policy Generator**
6. On the **Edit Permissions** page, select the following:
    - **Effect:** Allow
    - **AWS Service:** Amazon Polly
    - **Actions:** SynthesizeSpeech
    - **ARN:** *
7. Click on the **Add Statement** button
8. Click on **Next Step** then on **Apply Policy**

I apologize that this step is not clear in the instructions. I'll review the documentation to make this step more prominent. Please let me know if this fixes it or if you have further questions/comments.

Thanks for bringing this to our attention

-- Oliver

**Comment by SuneetPatil** [comment]
Hi Oliver,

Thanks for your response. It worked like charm. it saved my time.

--Suneet
