### ISSUE TITLE
Prompt Response Cards not displayed on Mobile Hub Deployment

### ISSUE THREAD

**Issue by meeshu** [awslabs/aws-lex-web-ui#9]
Hi Team,

I have deployed the sample lex order flower bot on Mobile Hub and added a response card in the Lex bot using Prompt Response Card. However, I am unable to render the Response cards. There are no errors- it just displays the text message. How can I fix it? 

Thanks!

**Comment by atoa** [comment]
Hello,

Couple of questions to better troubleshoot this:

1) Are you using text or voice?
2) If you look at the response in the [Network tab of Developer Tools](https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#response), do you see a `responseCard` field being returned?

Feel free to post a link to the application here as that may help to pinpoint the issue

-- Oliver

**Comment by meeshu** [comment]
Hey Oliver,

Thanks for the heads-up! I didn't realize that it worked only with text and not voice. Is there a way to make it work with both? Here's the url: http://lexorderflower-hosting-mobilehub-769249220.s3-website-us-east-1.amazonaws.com/ 

-- Meeshu

**Comment by atoa** [comment]
H Meeshu,

> Is there a way to make it work with both?

Yes. Although the Lex service only supports response cards with text, the web UI implements a workaround which uses a custom [session attribute](http://docs.aws.amazon.com/lex/latest/dg/context-mgmt.html#context-mgmt-session-attribs) to return a response card when using voice. This requires the bot to use a Lambda function to set the session attribute  (see the Lex documentation for [using Lambda functions](http://docs.aws.amazon.com/lex/latest/dg/using-lambda.html)).

For details about this custom voice-compatible response card, see the [Response Cards](https://github.com/awslabs/aws-lex-web-ui/tree/master/lex-web-ui#response-cards) section in the README of the Lex Web UI component.

Let me know if this clarifies it.

-- Oliver

**Comment by atoa** [comment]
Closing this issue as it seems like the question was answered. Feel free to reopen otherwise.
